spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/your_db_name
    redis:
      host: localhost
      port: 6379
      timeout: 6000ms
      
resilience4j:
  circuitbreaker:
    instances:
      bookServiceCircuitBreaker:
        failureRateThreshold: 50
        minimumNumberOfCalls: 10
        waitDurationInOpenState: 20s
        permittedNumberOfCallsInHalfOpenState: 5
        slidingWindowSize: 100
